"""Utility helpers for generating and validating example input files."""

import os
import shutil
import subprocess
from pathlib import Path


def generate_example_inputs():
    """Run the example input generator scripts for wind and solar.

    Executes the following scripts in order so the corresponding Feather files are
    produced under `examples/inputs`:

    - examples/inputs/00_generate_wind_history_small.py -> wind_input_small.ftr
        and scada_input.ftr
    - examples/inputs/01_generate_wind_history_large.py -> wind_input_large.ftr
    - examples/inputs/02_generate_solar_history.py -> solar_input.ftr

    Raises:
        subprocess.CalledProcessError: If any script returns a non-zero exit code.
    """

    repo_root = Path(__file__).resolve().parent.parent
    inputs_dir = repo_root / "examples" / "inputs"

    scripts = [
        inputs_dir / "00_generate_wind_history_small.py",
        inputs_dir / "01_generate_wind_history_large.py",
        inputs_dir / "02_generate_solar_history.py",
        inputs_dir / "07_generate_scada_power_playback.py",
    ]

    for script_path in scripts:
        subprocess.run(["python", str(script_path)], check=True, cwd=inputs_dir)


def ensure_example_inputs_exist():
    """Ensure example input Feather files exist; generate them if missing.

    Checks for the presence of the following files under `examples/inputs`:

    - wind_input_small.ftr
    - wind_input_large.ftr
    - solar_input.ftr
    - power_playback_input.ftr

    If any are missing, all example inputs will be (re)generated by calling
    `generate_example_inputs`.
    """

    repo_root = Path(__file__).resolve().parent.parent
    inputs_dir = repo_root / "examples" / "inputs"

    expected_files = [
        inputs_dir / "wind_input_small.ftr",
        inputs_dir / "wind_input_large.ftr",
        inputs_dir / "solar_input.ftr",
        inputs_dir / "scada_input.ftr",
        inputs_dir / "power_playback_input.ftr",
    ]

    if not all(p.exists() for p in expected_files):
        generate_example_inputs()


def prepare_output_directory(output_dir="outputs"):
    """Remove and recreate an output directory for clean runs.

    If the output directory exists, it will be deleted and recreated.
    This ensures a clean output directory before running examples.

    Args:
        output_dir (str, optional): Path to the output directory to prepare.
            Defaults to "outputs".
    """
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir)
