name: deploy-pages

on:
  push:
    branches:
    - develop
    paths:
    - docs/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -e ".[docs]"
    
    - name: Make copies of example docs
      run: |
        mkdir -vp docs/examples

        cp -v examples/00_wind_farm_only/README.md docs/examples/00_wind_farm_only.md
        cp -v examples/01_wind_farm_dof1_model/README.md docs/examples/01_wind_farm_dof1_model.md
        cp -v examples/02_wind_farm_realistic_inflow/README.md docs/examples/02_wind_farm_realistic_inflow.md
        cp -v examples/02b_wind_farm_realistic_inflow_precom_floris/README.md docs/examples/02b_wind_farm_realistic_inflow_precom_floris.md
        cp -v examples/03_wind_and_solar/README.md docs/examples/03_wind_and_solar.md
        cp -v examples/04_wind_and_storage/README.md docs/examples/04_wind_and_storage.md
        ls -l docs/examples

    # Build the book
    - name: Build the book
      working-directory: ${{runner.workspace}}/hercules/docs/
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
